<html>
<head>
<title>All in One Pet Service</title>

<script language="javascript">
<!--
home=new Image(75,35);home.src="imgs/home.png";
services=new Image(95,35);services.src="imgs/services.png";
contact=new Image(100,35);contact.src="imgs/contact.png";
links=new Image(122,35);links.src="imgs/links.png";
staff=new Image(70,35);staff.src="imgs/staff.png";
references=new Image(115,35);references.src="imgs/references.png";
cared=new Image(170,35);cared.src="imgs/cared.png";

homep=new Image(75,35);homep.src="imgs/home-p.png";
servicesp=new Image(95,35);servicesp.src="imgs/services-p.png";
contactp=new Image(100,35);contactp.src="imgs/contact-p.png";
linksp=new Image(122,35);linksp.src="imgs/links-p.png";
staffp=new Image(70,35);staffp.src="imgs/staff-p.png";
referencesp=new Image(115,35);referencesp.src="imgs/references-p.png";
caredp=new Image(170,35);caredp.src="imgs/cared-p.png";

function mouse(imgDocID, imgObjName, comment) {
document.images[imgDocID].src = eval(imgObjName + ".src");
window.status = comment; 
return true;
}

//-->
</script>

<script src="tips.js" type="text/javascript"></script>

<style type="text/css">
h2 {font-family: arial; 
    font-weight: bolder; 
    color: #ff0000;
    font-size: 28pt;
    text-align: center;}
    
td {font-family: arial;
    color: #000000;
    font-size: 11pt;
    }

#menu {
width: 100%;
background: #000;
float: left;
}
#menu ul {
list-style: none;
margin: 0;
padding: 0;
width: 12em;
float: left;
}

#menu a, #menu h2 {
font: bold 11px/16px arial, helvetica, sans-serif;
display: block;
margin: 0;
padding: 0px 0px;
}

#menu h2 {
color: #fff;
background: #000;
}

#menu a {
color: #fff100;
background: #000000;
text-decoration: none;
}

#menu a:hover {
color: #000000;
background: #fff100;
text-decoration: none;
}

#menu li {position: relative;}

#menu ul ul {
position: absolute;
text-align:left;
z-index: 500;
}

#menu ul ul ul {
top: 0;
left: 100%;
}

div#menu ul ul,
div#menu ul li:hover ul ul,
div#menu ul ul li:hover ul ul
{display: none;}

div#menu ul li:hover ul,
div#menu ul ul li:hover ul,
div#menu ul ul ul li:hover ul
{display: block;}
</style>
<!--[if IE]>
<style type="text/css" media="screen">
body {
behavior: url(csshover.htc);
font-size: 100%;
}

#menu ul li {float: left; width: 100%;}
#menu ul li a {height: 1%;} 

#menu a, #menu h2 {
font: bold .75em/1.5em arial, helvetica, sans-serif;
}
</style>
<![endif]-->


</head>
<body bgcolor="#ffffff">
<div align="center">


<table cellspacing="0" cellpadding="0" border="0" width="821">
<tr>
<td colspan="3" width="821"><img src="imgs/logo.gif" width="821" height="176"></td>
</tr>
<tr><td bgcolor="#ffffff" width="21"></td>
<td bgcolor="#000000" width="30"></td>
<td valign="top" bgcolor="#000000" width="765" align="left">

<div id="menu">

<ul style="width:75px;">
  <li><h2><a href="index.html" onMouseOver="mouse('home','homep','')" onMouseOut="mouse('home','home','')">
    <img src="imgs/home.png" name="home" border="0" width="75" height="35"></a></h2>
  </li>
</ul>

<ul style="width:95px">
  <li><h2><a href="" onMouseOver="mouse('services','servicesp','')" onMouseOut="mouse('services','services','')">
    <img src="imgs/services.png" name="services" border="0" width="95" height="35"></a></h2>
    <ul>
      <li><a href="training.html" title="Obedience Training and Animal Behavior Modification">&nbsp;&nbsp;Behavior &amp; Obedience Training</a></li>
      <li><a href="petsitting.html" title="Pet Sitting">&nbsp;&nbsp;Pet Sitting</a></li>
      <li><a href="walks.html" title="Daily Walks">&nbsp;&nbsp;Daily Walks</a></li>
      <li><a href="park.html" title="Dog Park">&nbsp;&nbsp;Dog Park</a></li>
      <li><a href="transport.html" title="Pet Transport">&nbsp;&nbsp;Pet Transport</a></li>
      <li><a href="firstaid.html" title="Pet First Aid &amp Care">&nbsp;&nbsp;Pet First Aid &amp; Care</a></li>
      <li><a href="cleanup.html" title="Yard Cleanup Services">&nbsp;&nbsp;Yard Clean Up Services</a></li>
      <li><a href="massage.html" title="Canine Massage">&nbsp;&nbsp;Canine Massage</a></li>
    </ul>
  </li>
</ul>

<ul style="width:70px">
  <li><h2><a href="" onMouseOver="mouse('staff','staffp','')" onMouseOut="mouse('staff','staff','')">
    <img src="imgs/staff.png" name="staff" border="0" width="70" height="35"></a></h2>
    <ul>
      <li><a href="theer.html" title="Karen Theer">&nbsp;&nbsp;Karen Theer</a></li>
      <li><a href="vanpelt.html" title="Judy VanPelt">&nbsp;&nbsp;Judy VanPelt</a></li>
      <li><a href="bassa.html" title="Anita Bassa">&nbsp;&nbsp;Anita Bassa</a></li>
      <li><a href="durnye.html" title="Vicky Durnye">&nbsp;&nbsp;Vicky Durnye</a></li>
      <li><a href="peterson.html" title="Matt Peterson">&nbsp;&nbsp;Matt Peterson</a></li>
    </ul>
  </li>
</ul>

<ul style="width:115px">
  <li><h2><a href="references.html" onMouseOver="mouse('references','referencesp','')" onMouseOut="mouse('references','references','')">
    <img src="imgs/references.png" name="references" border="0" width="115" height="35"></a></h2>
  </li>
</ul>

<ul style="width:122px">
  <li><h2><a href="links.html" onMouseOver="mouse('links','linksp','')" onMouseOut="mouse('links','links','')">
     <img src="imgs/links.png" name="links" border="0" width="122" height="35"></a></h2>
  </li>
</ul>

<ul style="width:170px">
  <li><h2><a href="cared.html" onMouseOver="mouse('cared','caredp','')" onMouseOut="mouse('cared','cared','')">
    <img src="imgs/cared.png" name="cared" border="0" width="170" height="35"></a></h2>
  </li>
</ul>

<ul style="width:100px">
  <li><h2><a href="contact.html" onMouseOver="mouse('contact','contactp','')" onMouseOut="mouse('contact','contact','')">
    <img src="imgs/contact.png" name="contact" border="0" width="100" height="35"></a></h2>
  </li>
</ul>
</div>

<br>
</td></tr>
<tr>
<td width="21" bgcolor="#ffffff"><font color="#ffffff"></font></td>
<td width="800" colspan="2" align="right" bgcolor="#000000">

<table width="800" cellpadding="15" cellspacing="0" border="0">
<tr><td valign="top" width="200" bgcolor="#000000">
<font size="2" color="#ffff00"><b><br>
Random Pet Tip:
</b><i>
<script language="javascript">
tip();
</script>

</i>
</font>
</td>
<td width="590" bgcolor="#ffffff">
